{
  "version": 2, 
  "jobs": {
    "build": {
      "working_directory": "~/repo", 
      "docker": [
        {
          "image": "circleci/node:10.16.3"
        }
      ], 
      "steps": [
        "checkout", 
        {
          "add_ssh_keys": {
            "fingerprints": [
              "$AZURE_VM_SSH_FINGERPRINT"
            ]
          }
        }, 
        {
          "run": {
            "command": "scp -o StrictHostKeyChecking=no -r ./* $AZURE_VM_USER@$AZURE_VM_IP:~/myapp", 
            "name": "Copy updated files to VM"
          }
        }
      ]
    }, 
    "deploy": {
      "machine": {
        "enabled": true
      }, 
      "steps": [
        {
          "run": {
            "command": "ssh $AZURE_VM_USER@$AZURE_VM_IP \"cd myapp && sudo npm run-script stop && sudo npm install && sudo npm start\"\n", 
            "name": "Deploy Over SSH"
          }
        }
      ]
    }
  }, 
  "workflows": {
    "version": 2, 
    "build": {
      "jobs": [
        {
          "build": null, 
          "filters": {
            "branches": {
              "only": "main"
            }
          }
        }, 
        {
          "deploy": {
            "requires": [
              "build"
            ], 
            "filters": {
              "branches": {
                "only": "main"
              }
            }
          }
        }
      ]
    }
  }
}